pub mod library;
pub mod executable;

use std::fs;
use crate::manifest::Target;
use library::generate_library_makefile;
use executable::generate_executable_makefile;
use crate::generators::Generator;


pub struct MakefileGenerator {}

impl MakefileGenerator {
	pub fn new() -> MakefileGenerator {
		MakefileGenerator {}
	}
}

impl Generator for MakefileGenerator {
	fn generate(&self, targets: &[Target]) -> std::io::Result<()> {
	    fs::create_dir_all("./.basalt/targets")?;

	    let mut master_makefile = String::new();
	    master_makefile.push_str("# Notice: These Makefiles are generated by Basalt - please don't edit.\n\n");
	    master_makefile.push_str("SOURCES_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)\n\n");

	    master_makefile.push_str("# Terminal formatting checks\n");
	    master_makefile.push_str("COLOR_SUPPORT := $(shell [ -t 1 ] && echo \"yes\" || echo \"no\")\n");
	    master_makefile.push_str("ifeq ($(COLOR_SUPPORT),yes)\n");
	    master_makefile.push_str("  C_GREEN  := \\033[0;32m\n");
	    master_makefile.push_str("  C_CYAN   := \\033[0;36m\n");
	    master_makefile.push_str("  C_YELLOW := \\033[0;33m\n");
	    master_makefile.push_str("  C_RESET  := \\033[0m\n");
	    master_makefile.push_str("else\n");
	    master_makefile.push_str("  C_GREEN  :=\n");
	    master_makefile.push_str("  C_CYAN   :=\n");
	    master_makefile.push_str("  C_YELLOW :=\n");
	    master_makefile.push_str("  C_RESET  :=\n");
	    master_makefile.push_str("endif\n\n");

	    let target_names: Vec<String> = targets.iter().map(|t| match t {
	        Target::Executable(e) => e.name.clone(),
	        Target::Library(l) => l.name.clone(),
	    }).collect();

	    master_makefile.push_str(&format!("all: {}\n\n", target_names.join(" ")));

	    for target in targets {
	        if let Target::Library(lib) = target {
	            master_makefile.push_str(&format!("include targets/{}/Makefile\n", lib.name));
	            generate_library_makefile(lib)?;
	        }
	    }
	    for target in targets {
	        if let Target::Executable(exec) = target {
	            master_makefile.push_str(&format!("include targets/{}/Makefile\n", exec.name));
	            generate_executable_makefile(exec)?;
	        }
	    }

	    master_makefile.push_str("\n.PHONY: all clean\n");
	    master_makefile.push_str("clean:\n");
	    master_makefile.push_str("\t@rm -rf $(ALL_CLEAN_FILES)\n");

	    fs::write("./.basalt/Makefile", master_makefile)?;
	    Ok(())
	}
}
