pub mod library;
pub mod executable;

use std::fs;
use crate::manifest::Target;
use library::generate_library_ninja;
use executable::generate_executable_ninja;
use crate::generators::Generator;


pub struct NinjaGenerator {}

impl NinjaGenerator {
	pub fn new() -> NinjaGenerator {
		NinjaGenerator {}
	}
}

impl Generator for NinjaGenerator {
	fn generate(&self, targets: &[Target]) -> std::io::Result<()> {
	    fs::create_dir_all("./.basalt/targets")?;

	    let mut master = String::new();
	    master.push_str("# Notice: This file is generated by Basalt - please don't edit.\n\n");
	    master.push_str("ninja_required_version = 1.10\n\n");
	    master.push_str("builddir = .\n");
	    master.push_str("sources_root = ..\n\n");

	    master.push_str("# Toolchain-agnostic rules\n");
	    master.push_str("rule cc\n");
	    master.push_str("  command = $cc $cflags -MMD -MF $out.d -c $in -o $out\n");
	    master.push_str("  depfile = $out.d\n");
	    master.push_str("  deps = gcc\n");
	    master.push_str("  description = CC $out\n\n");

	    master.push_str("rule cxx\n");
	    master.push_str("  command = $cxx $cxxflags -MMD -MF $out.d -c $in -o $out\n");
	    master.push_str("  depfile = $out.d\n");
	    master.push_str("  deps = gcc\n");
	    master.push_str("  description = CXX $out\n\n");

	    master.push_str("rule ar\n");
	    master.push_str("  command = rm -f $out && $ar rcs $out $in\n");
	    master.push_str("  description = AR $out\n\n");

	    master.push_str("rule link_exe\n");
	    master.push_str("  command = $ld $in -o $out $ldflags\n");
	    master.push_str("  description = LD $out\n\n");

	    master.push_str("rule link_shared\n");
	    master.push_str("  command = $ld -shared $in -o $out $ldflags\n");
	    master.push_str("  description = LD $out\n\n");

	    let mut default_targets: Vec<String> = Vec::new();

	    for target in targets {
	        if let Target::Library(lib) = target {
	            master.push_str(&format!("subninja targets/{}/build.ninja\n", lib.name));
	            default_targets.push(lib.name.clone());
	            generate_library_ninja(lib)?;
	        }
	    }
	    for target in targets {
	        if let Target::Executable(exec) = target {
	            master.push_str(&format!("subninja targets/{}/build.ninja\n", exec.name));
	            default_targets.push(exec.name.clone());
	            generate_executable_ninja(exec)?;
	        }
	    }

	    master.push_str("\nbuild all: phony ");
	    master.push_str(&default_targets.join(" "));
	    master.push_str("\n\ndefault all\n");

	    fs::write("./.basalt/build.ninja", master)?;
	    Ok(())
	}
}
